import type { Strategy, PaginatedResponse } from "@/lib/types"

// Mock data for frontend development
const mockStrategies: Strategy[] = [
  {
    id: 1,
    name: "BTC Momentum",
    description: "Follows Bitcoin price momentum with 4-hour timeframe",
    status: "active",
    performance: 8.4,
    allocation: 25,
    risk: "medium",
    algorithm: "Momentum",
    timeframe: "4h",
    assets: "BTC",
    parameters: { lookback: 14, threshold: 0.05, stop_loss: 0.03 },
  },
  {
    id: 2,
    name: "ETH/BTC Ratio",
    description: "Trades based on Ethereum to Bitcoin price ratio",
    status: "active",
    performance: 12.7,
    allocation: 20,
    risk: "high",
    algorithm: "Ratio",
    timeframe: "1d",
    assets: "ETH,BTC",
    parameters: { ratio_threshold: 0.07, ma_period: 20 },
  },
  {
    id: 3,
    name: "DeFi Basket",
    description: "Algorithmic trading of top DeFi tokens",
    status: "paused",
    performance: -2.3,
    allocation: 15,
    risk: "high",
    algorithm: "Basket",
    timeframe: "1d",
    assets: "AAVE,UNI,COMP,SNX",
    parameters: { rebalance_period: 7, max_allocation: 0.3 },
  },
  {
    id: 4,
    name: "MACD Crossover",
    description: "MACD indicator strategy for major cryptocurrencies",
    status: "active",
    performance: 5.2,
    allocation: 15,
    risk: "medium",
    algorithm: "MACD",
    timeframe: "1d",
    assets: "BTC,ETH,SOL",
    parameters: { fast_period: 12, slow_period: 26, signal_period: 9 },
  },
  {
    id: 5,
    name: "Stablecoin Yield",
    description: "Optimizes yield farming with stablecoins",
    status: "active",
    performance: 1.8,
    allocation: 25,
    risk: "low",
    algorithm: "Yield",
    timeframe: "1d",
    assets: "USDC,USDT,DAI",
    parameters: { min_apy: 0.04, max_risk_score: 2 },
  },
  {
    id: 6,
    name: "Bollinger Bands",
    description: "Uses Bollinger Bands to identify overbought/oversold conditions",
    status: "active",
    performance: 6.7,
    allocation: 10,
    risk: "medium",
    algorithm: "Bollinger",
    timeframe: "4h",
    assets: "BTC,ETH,BNB",
    parameters: { period: 20, std_dev: 2, mean_reversion: true },
  },
  {
    id: 7,
    name: "RSI Divergence",
    description: "Identifies price divergence using RSI indicator",
    status: "active",
    performance: 9.3,
    allocation: 15,
    risk: "medium",
    algorithm: "RSI",
    timeframe: "1h",
    assets: "BTC,ETH,SOL",
    parameters: { rsi_period: 14, divergence_threshold: 0.1 },
  },
  {
    id: 8,
    name: "Layer 2 Portfolio",
    description: "Invests in Layer 2 scaling solutions",
    status: "active",
    performance: 15.2,
    allocation: 20,
    risk: "high",
    algorithm: "Portfolio",
    timeframe: "1d",
    assets: "MATIC,OP,ARB",
    parameters: { rebalance_threshold: 0.1, max_weight: 0.4 },
  },
  {
    id: 9,
    name: "NFT Market Index",
    description: "Tracks performance of NFT-related tokens",
    status: "paused",
    performance: -5.8,
    allocation: 10,
    risk: "high",
    algorithm: "Index",
    timeframe: "1d",
    assets: "APE,BLUR,SAND,MANA",
    parameters: { market_cap_weight: true, volume_threshold: 1000000 },
  },
  {
    id: 10,
    name: "Smart Contract Platforms",
    description: "Diversified portfolio of smart contract platforms",
    status: "active",
    performance: 7.5,
    allocation: 25,
    risk: "medium",
    algorithm: "Portfolio",
    timeframe: "1d",
    assets: "ETH,SOL,ADA,AVAX",
    parameters: { market_weight: true, min_liquidity: 5000000 },
  },
  {
    id: 11,
    name: "AI Tokens",
    description: "Invests in AI and machine learning tokens",
    status: "active",
    performance: 18.9,
    allocation: 15,
    risk: "high",
    algorithm: "Momentum",
    timeframe: "4h",
    assets: "FET,OCEAN,AGIX",
    parameters: { trend_strength: 0.7, position_size: 0.33 },
  },
  {
    id: 12,
    name: "Privacy Coins",
    description: "Portfolio of privacy-focused cryptocurrencies",
    status: "paused",
    performance: 3.2,
    allocation: 10,
    risk: "high",
    algorithm: "Equal Weight",
    timeframe: "1d",
    assets: "XMR,ZEC,SCRT",
    parameters: { rebalance_frequency: "weekly", slippage_tolerance: 0.02 },
  },
  {
    id: 13,
    name: "DeFi Yield",
    description: "Optimizes yield across DeFi protocols",
    status: "active",
    performance: 11.4,
    allocation: 20,
    risk: "medium",
    algorithm: "Yield",
    timeframe: "1d",
    assets: "AAVE,CRV,MKR",
    parameters: { min_yield: 0.05, max_protocol_exposure: 0.4 },
  },
  {
    id: 14,
    name: "Gaming Tokens",
    description: "Invests in blockchain gaming projects",
    status: "active",
    performance: -3.7,
    allocation: 15,
    risk: "high",
    algorithm: "Index",
    timeframe: "1d",
    assets: "AXS,SAND,ILV,ENJ",
    parameters: { volume_weighted: true, min_market_cap: 100000000 },
  },
  {
    id: 15,
    name: "Oracle Networks",
    description: "Tracks performance of blockchain oracles",
    status: "active",
    performance: 6.8,
    allocation: 15,
    risk: "medium",
    algorithm: "Equal Weight",
    timeframe: "1d",
    assets: "LINK,BAND,API3",
    parameters: { rebalance_threshold: 0.05, max_slippage: 0.01 },
  },
  {
    id: 16,
    name: "Metaverse Index",
    description: "Diversified exposure to metaverse tokens",
    status: "active",
    performance: 8.9,
    allocation: 20,
    risk: "high",
    algorithm: "Index",
    timeframe: "1d",
    assets: "MANA,SAND,AXS,ENJ",
    parameters: { cap_weighted: true, rebalance_frequency: "monthly" },
  },
  {
    id: 17,
    name: "Cross-chain Protocols",
    description: "Invests in cross-chain infrastructure",
    status: "paused",
    performance: 4.5,
    allocation: 15,
    risk: "medium",
    algorithm: "Portfolio",
    timeframe: "1d",
    assets: "ATOM,DOT,RUNE",
    parameters: { ecosystem_weight: 0.4, bridge_volume_weight: 0.6 },
  },
  {
    id: 18,
    name: "Lending Protocols",
    description: "Tracks major DeFi lending platforms",
    status: "active",
    performance: 9.7,
    allocation: 20,
    risk: "medium",
    algorithm: "TVL Weighted",
    timeframe: "1d",
    assets: "AAVE,COMP,QNT",
    parameters: { min_tvl: 500000000, max_weight: 0.4 },
  },
  {
    id: 19,
    name: "MEV Strategies",
    description: "Capitalizes on MEV opportunities",
    status: "active",
    performance: 12.3,
    allocation: 15,
    risk: "high",
    algorithm: "Arbitrage",
    timeframe: "5m",
    assets: "ETH,MATIC",
    parameters: { min_profit: 0.001, gas_threshold: 100 },
  },
  {
    id: 20,
    name: "Governance Tokens",
    description: "Invests in DAO governance tokens",
    status: "active",
    performance: 5.6,
    allocation: 15,
    risk: "medium",
    algorithm: "Equal Weight",
    timeframe: "1d",
    assets: "UNI,MKR,ENS",
    parameters: { voting_power_weight: true, min_holders: 1000 },
  },
  {
    id: 21,
    name: "Volatility Trading",
    description: "Profits from market volatility",
    status: "active",
    performance: 16.8,
    allocation: 10,
    risk: "high",
    algorithm: "Volatility",
    timeframe: "1h",
    assets: "BTC,ETH",
    parameters: { vol_threshold: 0.02, position_scaling: true },
  },
  {
    id: 22,
    name: "Liquid Staking",
    description: "Optimizes staking yields across protocols",
    status: "active",
    performance: 4.2,
    allocation: 20,
    risk: "low",
    algorithm: "Yield",
    timeframe: "1d",
    assets: "ETH,SOL,MATIC",
    parameters: { min_apr: 0.04, validator_diversification: true },
  },
  {
    id: 23,
    name: "Exchange Tokens",
    description: "Tracks performance of exchange tokens",
    status: "paused",
    performance: -1.8,
    allocation: 15,
    risk: "medium",
    algorithm: "Volume Weighted",
    timeframe: "1d",
    assets: "BNB,FTT,KCS",
    parameters: { exchange_volume_weight: 0.7, user_growth_weight: 0.3 },
  },
  {
    id: 24,
    name: "RWA Tokens",
    description: "Invests in real-world asset tokens",
    status: "active",
    performance: 3.5,
    allocation: 20,
    risk: "low",
    algorithm: "Portfolio",
    timeframe: "1d",
    assets: "MKR,USDC,PAXG",
    parameters: { asset_correlation: -0.2, min_liquidity: 1000000 },
  },
  {
    id: 25,
    name: "Zero Knowledge Protocols",
    description: "Focuses on ZK technology tokens",
    status: "active",
    performance: 14.7,
    allocation: 15,
    risk: "high",
    algorithm: "Innovation",
    timeframe: "1d",
    assets: "MATIC,ZEC,MINA",
    parameters: { tech_adoption_weight: 0.6, development_activity: 0.4 },
  },
  {
    id: 26,
    name: "Derivatives Protocols",
    description: "Tracks DeFi derivatives platforms",
    status: "active",
    performance: 7.9,
    allocation: 15,
    risk: "high",
    algorithm: "Volume",
    timeframe: "1d",
    assets: "SNX,DYDX,GMX",
    parameters: { trading_volume_weight: 0.8, open_interest_weight: 0.2 },
  },
  {
    id: 27,
    name: "Infrastructure Tokens",
    description: "Invests in blockchain infrastructure",
    status: "active",
    performance: 6.4,
    allocation: 20,
    risk: "medium",
    algorithm: "Portfolio",
    timeframe: "1d",
    assets: "GRT,FIL,AR",
    parameters: { usage_metrics_weight: 0.5, storage_growth_weight: 0.5 },
  },
  {
    id: 28,
    name: "Sustainability Tokens",
    description: "Focus on eco-friendly blockchains",
    status: "active",
    performance: 5.1,
    allocation: 15,
    risk: "medium",
    algorithm: "ESG",
    timeframe: "1d",
    assets: "ALGO,XRP,ADA",
    parameters: { energy_efficiency_score: 0.7, sustainability_rating: 0.3 },
  },
  {
    id: 29,
    name: "Identity Protocols",
    description: "Invests in blockchain identity solutions",
    status: "paused",
    performance: 2.8,
    allocation: 10,
    risk: "medium",
    algorithm: "Innovation",
    timeframe: "1d",
    assets: "ENS,CVC,CIVIC",
    parameters: { adoption_rate_weight: 0.6, integration_score: 0.4 },
  },
  {
    id: 30,
    name: "Social Tokens",
    description: "Tracks social media and content tokens",
    status: "active",
    performance: 9.4,
    allocation: 15,
    risk: "high",
    algorithm: "Social Metrics",
    timeframe: "1d",
    assets: "CHZ,THETA,AUDIO",
    parameters: { engagement_weight: 0.5, user_growth_weight: 0.5 },
  },
]

// This function will be replaced with actual API call
export async function fetchTradingStrategies(page = 1, limit = 6): Promise<PaginatedResponse<Strategy>> {
  // Simulate API call delay
  await new Promise((resolve) => setTimeout(resolve, 1000))

  // In production, this would be:
  // const response = await fetch(`/api/strategies?page=${page}&limit=${limit}`)
  // const data = await response.json()
  // return data

  // Calculate pagination
  const startIndex = (page - 1) * limit
  const endIndex = startIndex + limit
  const paginatedItems = mockStrategies.slice(startIndex, endIndex)
  const totalItems = mockStrategies.length
  const totalPages = Math.ceil(totalItems / limit)

  return {
    items: paginatedItems,
    page,
    limit,
    totalItems,
    totalPages,
  }
}

// This function will be replaced with actual API call
export async function updateStrategyStatus(id: number, status: "active" | "paused"): Promise<void> {
  // Simulate API call delay
  await new Promise((resolve) => setTimeout(resolve, 1000))

  // In production, this would be:
  // await fetch(`/api/strategies/${id}/status`, {
  //   method: 'PUT',
  //   headers: {
  //     'Content-Type': 'application/json',
  //   },
  //   body: JSON.stringify({ status }),
  // })

  console.log(`Strategy ${id} status updated to ${status}`)
}

// This function will be replaced with actual API call
export async function deleteStrategy(id: number): Promise<void> {
  // Simulate API call delay
  await new Promise((resolve) => setTimeout(resolve, 1000))

  // In production, this would be:
  // await fetch(`/api/strategies/${id}`, {
  //   method: 'DELETE',
  // })

  console.log(`Strategy ${id} deleted`)
}